name: Build Stupid Dog

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.3'

      - name: Install SDL2
        shell: powershell
        run: |
          vcpkg install sdl2:x64-windows
          echo "CMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" >> $env:GITHUB_ENV

      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$env:CMAKE_TOOLCHAIN_FILE

      - name: Build
        run: cmake --build build --config Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: StupidDog
          path: build
