name: Build Stupid Dog

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          toolset: 14

      - name: Download SDL2
        shell: cmd
        run: |
          curl -L -o SDL2.zip https://github.com/libsdl-org/SDL/releases/download/release-2.32.10/SDL2-devel-2.32.10-VC.zip
          powershell Expand-Archive SDL2.zip -DestinationPath .
          move SDL2-2.32.10 sdl2
          mklink /J sdl2\SDL2 sdl2\include

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10"
          host: windows
          target: desktop
          arch: win64_msvc2022_64

      - name: Configure
        shell: cmd
        run: >
          cmake -B build
          -G "Visual Studio 17 2022"
          -DSDL2_PATH=%CD%/sdl2/
          -DSDL2_LIBRARY=%CD%/sdl2/lib/x64/SDL2.lib
          -DSDL2_INCLUDE_DIR=%CD%/sdl2/include
          -DSDL2_DLL_LOCATION_DIR=%CD%/sdl2/lib/x64/SDL2.dll

      - name: Build
        run: cmake --build build --config Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: StupidDog
          path: build
